import type { GeneratedTheme } from '@/lib/localVibeThemes';

/** Official-ish brand palettes — HSL without wrapper. */
const BRAND_THEMES: Record<string, GeneratedTheme> = {
  nike: {
    themeName: 'Nike VYBE',
    colorPrimary: '0 0% 100%',
    colorSecondary: '0 0% 8%',
    colorAccent: '16 100% 50%',
    bgMain: '0 0% 4%',
    bgCard: '0 0% 8%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 65%',
    borderColor: '0 0% 18%',
    neonPink: '16 100% 50%',
    neonPurple: '0 0% 40%',
    neonCyan: '0 0% 90%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'particles',
    animationSpeed: 'fast',
    animationStyle: 'snappy',
  },
  apple: {
    themeName: 'Apple VYBE',
    colorPrimary: '0 0% 98%',
    colorSecondary: '0 0% 55%',
    colorAccent: '211 100% 50%',
    bgMain: '0 0% 0%',
    bgCard: '0 0% 7%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 62%',
    borderColor: '0 0% 16%',
    neonPink: '0 0% 85%',
    neonPurple: '211 100% 55%',
    neonCyan: '199 100% 50%',
    mode: 'dark',
    borderRadius: 'large',
    backgroundEffect: 'none',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  spotify: {
    themeName: 'Spotify VYBE',
    colorPrimary: '141 73% 42%',
    colorSecondary: '0 0% 7%',
    colorAccent: '141 76% 48%',
    bgMain: '0 0% 4%',
    bgCard: '0 0% 9%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 68%',
    borderColor: '141 30% 16%',
    neonPink: '141 73% 42%',
    neonPurple: '280 60% 55%',
    neonCyan: '141 76% 48%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'aurora',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  cocacola: {
    themeName: 'Coca-Cola VYBE',
    colorPrimary: '0 84% 50%',
    colorSecondary: '0 0% 8%',
    colorAccent: '0 0% 98%',
    bgMain: '0 50% 5%',
    bgCard: '0 40% 9%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 20% 72%',
    borderColor: '0 40% 18%',
    neonPink: '0 84% 50%',
    neonPurple: '0 70% 45%',
    neonCyan: '0 0% 95%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'particles',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  mcdonalds: {
    themeName: "McDonald's VYBE",
    colorPrimary: '0 84% 50%',
    colorSecondary: '45 100% 50%',
    colorAccent: '45 100% 55%',
    bgMain: '0 40% 6%',
    bgCard: '0 35% 10%',
    textPrimary: '45 30% 96%',
    textSecondary: '45 15% 70%',
    borderColor: '0 35% 18%',
    neonPink: '0 84% 50%',
    neonPurple: '45 100% 50%',
    neonCyan: '45 100% 60%',
    mode: 'dark',
    borderRadius: 'large',
    backgroundEffect: 'particles',
    animationSpeed: 'fast',
    animationStyle: 'bouncy',
  },
  instagram: {
    themeName: 'Instagram VYBE',
    colorPrimary: '330 85% 58%',
    colorSecondary: '280 75% 55%',
    colorAccent: '25 95% 55%',
    bgMain: '280 30% 6%',
    bgCard: '280 25% 10%',
    textPrimary: '0 0% 98%',
    textSecondary: '280 10% 68%',
    borderColor: '330 30% 18%',
    neonPink: '330 85% 58%',
    neonPurple: '280 75% 55%',
    neonCyan: '25 95% 55%',
    mode: 'dark',
    borderRadius: 'large',
    backgroundEffect: 'aurora',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  discord: {
    themeName: 'Discord VYBE',
    colorPrimary: '235 86% 65%',
    colorSecondary: '225 30% 12%',
    colorAccent: '153 60% 52%',
    bgMain: '225 30% 7%',
    bgCard: '225 28% 11%',
    textPrimary: '0 0% 98%',
    textSecondary: '225 10% 68%',
    borderColor: '235 30% 20%',
    neonPink: '235 86% 65%',
    neonPurple: '270 70% 60%',
    neonCyan: '153 60% 52%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'stars',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  netflix: {
    themeName: 'Netflix VYBE',
    colorPrimary: '0 82% 50%',
    colorSecondary: '0 0% 6%',
    colorAccent: '0 82% 55%',
    bgMain: '0 0% 3%',
    bgCard: '0 0% 8%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 65%',
    borderColor: '0 40% 16%',
    neonPink: '0 82% 50%',
    neonPurple: '0 70% 45%',
    neonCyan: '0 0% 90%',
    mode: 'dark',
    borderRadius: 'small',
    backgroundEffect: 'none',
    animationSpeed: 'normal',
    animationStyle: 'snappy',
  },
  tesla: {
    themeName: 'Tesla VYBE',
    colorPrimary: '0 82% 50%',
    colorSecondary: '0 0% 10%',
    colorAccent: '0 0% 95%',
    bgMain: '0 0% 2%',
    bgCard: '0 0% 7%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 62%',
    borderColor: '0 0% 16%',
    neonPink: '0 82% 50%',
    neonPurple: '0 0% 50%',
    neonCyan: '0 0% 92%',
    mode: 'dark',
    borderRadius: 'small',
    backgroundEffect: 'geometric',
    animationSpeed: 'fast',
    animationStyle: 'snappy',
  },
  starbucks: {
    themeName: 'Starbucks VYBE',
    colorPrimary: '160 100% 22%',
    colorSecondary: '160 40% 12%',
    colorAccent: '45 80% 55%',
    bgMain: '160 35% 5%',
    bgCard: '160 30% 9%',
    textPrimary: '140 25% 96%',
    textSecondary: '150 15% 68%',
    borderColor: '160 30% 16%',
    neonPink: '160 100% 22%',
    neonPurple: '160 60% 35%',
    neonCyan: '45 80% 55%',
    mode: 'dark',
    borderRadius: 'large',
    backgroundEffect: 'fireflies',
    animationSpeed: 'slow',
    animationStyle: 'smooth',
  },
  tiffany: {
    themeName: 'Tiffany VYBE',
    colorPrimary: '178 68% 52%',
    colorSecondary: '178 40% 90%',
    colorAccent: '178 75% 45%',
    bgMain: '178 30% 96%',
    bgCard: '0 0% 100%',
    textPrimary: '178 40% 12%',
    textSecondary: '178 15% 38%',
    borderColor: '178 30% 85%',
    neonPink: '178 68% 52%',
    neonPurple: '200 60% 55%',
    neonCyan: '178 75% 45%',
    mode: 'light',
    borderRadius: 'large',
    backgroundEffect: 'bubbles',
    animationSpeed: 'slow',
    animationStyle: 'smooth',
  },
  supreme: {
    themeName: 'Supreme VYBE',
    colorPrimary: '0 85% 50%',
    colorSecondary: '0 0% 5%',
    colorAccent: '0 0% 98%',
    bgMain: '0 0% 4%',
    bgCard: '0 0% 8%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 62%',
    borderColor: '0 50% 16%',
    neonPink: '0 85% 50%',
    neonPurple: '0 70% 45%',
    neonCyan: '0 0% 95%',
    mode: 'dark',
    borderRadius: 'small',
    backgroundEffect: 'particles',
    animationSpeed: 'fast',
    animationStyle: 'snappy',
  },
  adidas: {
    themeName: 'Adidas VYBE',
    colorPrimary: '0 0% 98%',
    colorSecondary: '0 0% 8%',
    colorAccent: '0 0% 55%',
    bgMain: '0 0% 4%',
    bgCard: '0 0% 9%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 65%',
    borderColor: '0 0% 18%',
    neonPink: '0 0% 90%',
    neonPurple: '0 0% 50%',
    neonCyan: '0 0% 75%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'geometric',
    animationSpeed: 'fast',
    animationStyle: 'snappy',
  },
  google: {
    themeName: 'Google VYBE',
    colorPrimary: '217 89% 55%',
    colorSecondary: '4 82% 55%',
    colorAccent: '45 98% 50%',
    bgMain: '220 20% 97%',
    bgCard: '0 0% 100%',
    textPrimary: '220 25% 12%',
    textSecondary: '220 10% 42%',
    borderColor: '220 15% 88%',
    neonPink: '4 82% 55%',
    neonPurple: '270 60% 55%',
    neonCyan: '217 89% 55%',
    mode: 'light',
    borderRadius: 'large',
    backgroundEffect: 'bubbles',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  youtube: {
    themeName: 'YouTube VYBE',
    colorPrimary: '0 100% 50%',
    colorSecondary: '0 0% 8%',
    colorAccent: '0 0% 98%',
    bgMain: '0 0% 4%',
    bgCard: '0 0% 9%',
    textPrimary: '0 0% 98%',
    textSecondary: '0 0% 65%',
    borderColor: '0 40% 16%',
    neonPink: '0 100% 50%',
    neonPurple: '0 80% 45%',
    neonCyan: '0 0% 92%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'particles',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  amazon: {
    themeName: 'Amazon VYBE',
    colorPrimary: '36 100% 50%',
    colorSecondary: '210 50% 15%',
    colorAccent: '36 100% 55%',
    bgMain: '210 40% 6%',
    bgCard: '210 35% 10%',
    textPrimary: '0 0% 98%',
    textSecondary: '210 15% 68%',
    borderColor: '210 30% 18%',
    neonPink: '36 100% 50%',
    neonPurple: '210 50% 45%',
    neonCyan: '36 100% 55%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'aurora',
    animationSpeed: 'normal',
    animationStyle: 'smooth',
  },
  roblox: {
    themeName: 'Roblox VYBE',
    colorPrimary: '0 0% 10%',
    colorSecondary: '0 0% 95%',
    colorAccent: '0 82% 50%',
    bgMain: '220 15% 8%',
    bgCard: '220 12% 12%',
    textPrimary: '0 0% 98%',
    textSecondary: '220 10% 68%',
    borderColor: '0 40% 18%',
    neonPink: '0 82% 50%',
    neonPurple: '220 60% 55%',
    neonCyan: '199 90% 50%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'geometric',
    animationSpeed: 'fast',
    animationStyle: 'bouncy',
  },
  fortnite: {
    themeName: 'Fortnite VYBE',
    colorPrimary: '260 85% 58%',
    colorSecondary: '45 100% 50%',
    colorAccent: '199 95% 55%',
    bgMain: '260 30% 6%',
    bgCard: '260 25% 10%',
    textPrimary: '0 0% 98%',
    textSecondary: '260 10% 68%',
    borderColor: '260 30% 18%',
    neonPink: '260 85% 58%',
    neonPurple: '280 80% 60%',
    neonCyan: '199 95% 55%',
    mode: 'dark',
    borderRadius: 'medium',
    backgroundEffect: 'particles',
    animationSpeed: 'fast',
    animationStyle: 'bouncy',
  },
};

const BRAND_ALIASES: Array<{ id: string; pattern: RegExp }> = [
  { id: 'nike', pattern: /\b(nike|jordan|air max|swoosh)\b/i },
  { id: 'apple', pattern: /\b(apple|iphone|ios|macbook|ipad)\b/i },
  { id: 'spotify', pattern: /\b(spotify)\b/i },
  { id: 'cocacola', pattern: /\b(coca[\s-]?cola|coke)\b/i },
  { id: 'mcdonalds', pattern: /\b(mcdonald'?s|mcdonalds|golden arches)\b/i },
  { id: 'instagram', pattern: /\b(instagram|insta)\b/i },
  { id: 'discord', pattern: /\b(discord)\b/i },
  { id: 'netflix', pattern: /\b(netflix)\b/i },
  { id: 'tesla', pattern: /\b(tesla)\b/i },
  { id: 'starbucks', pattern: /\b(starbucks)\b/i },
  { id: 'tiffany', pattern: /\b(tiffany|tiffany & co)\b/i },
  { id: 'supreme', pattern: /\b(supreme)\b/i },
  { id: 'adidas', pattern: /\b(adidas|three stripes)\b/i },
  { id: 'google', pattern: /\b(google|android)\b/i },
  { id: 'youtube', pattern: /\b(youtube|yt)\b/i },
  { id: 'amazon', pattern: /\b(amazon|aws)\b/i },
  { id: 'roblox', pattern: /\b(roblox)\b/i },
  { id: 'fortnite', pattern: /\b(fortnite|epic games)\b/i },
];

export function detectBrandFromPrompt(prompt: string): string | null {
  const text = prompt.trim();
  if (!text) return null;
  for (const { id, pattern } of BRAND_ALIASES) {
    if (pattern.test(text)) return id;
  }
  return null;
}

export function buildBrandTheme(brandId: string): GeneratedTheme | null {
  const theme = BRAND_THEMES[brandId];
  return theme ? { ...theme } : null;
}

/** Extra instructions for AI when a brand is detected. */
export function brandThemePromptHint(brandId: string): string {
  const theme = BRAND_THEMES[brandId];
  if (!theme) return '';
  return [
    `Match the real-world brand "${theme.themeName?.replace(' VYBE', '')}" as closely as possible.`,
    `Use these exact HSL anchors — primary: ${theme.colorPrimary}, secondary: ${theme.colorSecondary}, accent: ${theme.colorAccent}.`,
    `Background mood: ${theme.mode === 'light' ? 'light clean' : 'dark premium'}.`,
    'Do not invent unrelated neon colors; stay on-brand.',
  ].join(' ');
}
