import {act,cleanup,fireEvent,render,renderHook,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({uid:'alice',profile:'profile-alice',epoch:1,invoke:vi.fn(),signOut:vi.fn(),collect:vi.fn()}));
vi.mock('@/lib/firebase/functionsService',()=>({invokeFunction:(...args:unknown[])=>state.invoke(...args)}));
vi.mock('@/lib/auth',()=>({useAuth:()=>({user:{id:state.uid},profile:{id:state.profile,user_id:state.uid},signOut:state.signOut})}));
vi.mock('@/hooks/useVerifiedSettingsScope',()=>({useVerifiedSettingsScope:()=>({account:{uid:state.uid,epoch:state.epoch},profileId:state.profile,creationTime:'2026-01-01',ready:true,capture:()=>{const uid=state.uid,profile=state.profile,epoch=state.epoch;return{fields:{expectedOwnerUid:uid,expectedProfileId:profile,expectedAccountCreatedAt:1},guard:()=>{if(uid!==state.uid||profile!==state.profile||epoch!==state.epoch)throw new Error('Account changed')}}}})}));
vi.mock('@/lib/accountDataExport',()=>({collectAccountDataExport:(...args:unknown[])=>state.collect(...args)}));
import {checkedDeletionRequest,useAccountDeletion} from './useAccountDeletion';
import {AccountDangerZone} from '@/components/settings/AccountDangerZone';
const first='a'.repeat(48),second='b'.repeat(48);
const date='2026-01-01T00:00:00.000Z',due='2026-01-31T00:00:00.000Z';
function ack(request:any,extra={}){return{ok:true,version:2,ownerUid:request.expectedOwnerUid,profileId:request.expectedProfileId,accountCreatedAt:request.expectedAccountCreatedAt,requestId:request.requestId,status:'none',revision:null,requestedAt:null,eligibleAfter:null,automaticCleanup:false,...extra}}
function pending<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>resolve=yes);return{promise,resolve}}
const scope={fields:{expectedOwnerUid:'alice',expectedProfileId:'profile-alice',expectedAccountCreatedAt:1},guard:()=>{}};
beforeEach(()=>{vi.clearAllMocks();state.uid='alice';state.profile='profile-alice';state.epoch++;Object.defineProperty(navigator,'onLine',{configurable:true,value:true});window.dispatchEvent(new Event('app-resumed'));state.invoke.mockImplementation(async(_name,request)=>({data:ack(request),error:null}));});
afterEach(()=>{cleanup();vi.useRealTimers();Object.defineProperty(navigator,'onLine',{configurable:true,value:true});window.dispatchEvent(new Event('app-resumed'));});
describe('checked deletion request protocol and actual controls',()=>{
  it('shows a failed request inside its open confirmation and requires refresh before retry',async()=>{let fail=true;state.invoke.mockImplementation(async(_name,request)=>request.action==='request_delete'&&fail ? {data:null,error:{message:'Temporary request failure'}}:{data:ack(request,request.action==='request_delete'?{status:'pending_review',revision:first,requestedAt:date,eligibleAfter:due}:{}),error:null});render(<AccountDangerZone/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'}));fireEvent.change(screen.getByPlaceholderText('Type DELETE'),{target:{value:'DELETE'}});fireEvent.click(screen.getByRole('button',{name:'Request deletion',exact:true}));expect(await screen.findByRole('alert')).toHaveTextContent('Temporary request failure');expect(screen.getByRole('button',{name:'Request deletion',exact:true})).toBeDisabled();const original=state.invoke.mock.calls[1][1];fail=false;fireEvent.click(screen.getByRole('button',{name:'Refresh deletion status'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Request deletion',exact:true})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Request deletion',exact:true}));await screen.findByText('Deletion request recorded');expect(state.invoke.mock.calls[3][1].requestId).toBe(original.requestId);expect(state.signOut).not.toHaveBeenCalled();});
  it('read then request then cancel uses checked revisions and does not sign out or erase a profile',async()=>{let value:any={status:'none',revision:null,requestedAt:null,eligibleAfter:null};state.invoke.mockImplementation(async(_name,request)=>{if(request.action==='request_delete')value={status:'pending_review',revision:first,requestedAt:date,eligibleAfter:due};if(request.action==='cancel_delete')value={...value,status:'cancelled',revision:second};return{data:ack(request,value),error:null}});render(<AccountDangerZone/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'}));fireEvent.change(screen.getByPlaceholderText('Type DELETE'),{target:{value:'DELETE'}});fireEvent.click(screen.getByRole('button',{name:'Request deletion',exact:true}));await screen.findByText('Deletion request recorded');expect(screen.getByText(/Permanent cleanup is not automatic yet. You can cancel/)).toBeVisible();expect(state.invoke.mock.calls[1][1]).toMatchObject({expectedRevision:null,expectedOwnerUid:'alice',action:'request_delete'});fireEvent.click(screen.getByRole('button',{name:'Cancel account deletion request'}));await screen.findByText('Your deletion request is cancelled.');expect(state.invoke.mock.calls[2][1]).toMatchObject({expectedRevision:first,action:'cancel_delete'});expect(state.signOut).not.toHaveBeenCalled();});
  it.each(['ownerUid','profileId','accountCreatedAt','requestId','version','automaticCleanup','status','revision','eligibleAfter'])('rejects unsafe acknowledgment %s',async field=>{state.invoke.mockImplementation(async(_name,request)=>({data:{...ack(request),[field]:'wrong'},error:null}));await expect(checkedDeletionRequest(scope,{action:'deletion_status'})).rejects.toThrow('could not be verified');});
  it('rejects the inherited ok-only stub and exposes retry instead of success',async()=>{state.invoke.mockResolvedValue({data:{ok:true,success:true},error:null});render(<AccountDangerZone/>);await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'})).toBeDisabled();expect(screen.queryByText('Deletion request recorded')).not.toBeInTheDocument();state.invoke.mockImplementation(async(_name,request)=>({data:ack(request),error:null}));fireEvent.click(screen.getByRole('button',{name:'Retry deletion status'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Request account deletion with a 30-day grace period'})).toBeEnabled());});
  it('serializes requests synchronously before React rerenders',async()=>{const task=pending<any>();let mutation:any;state.invoke.mockImplementation(async(_name,request)=>{if(request.action==='deletion_status')return{data:ack(request),error:null};mutation=request;return task.promise});const hook=renderHook(()=>useAccountDeletion());await waitFor(()=>expect(hook.result.current.ready).toBe(true));let firstRun!:Promise<any>,secondRun!:Promise<any>;await act(async()=>{firstRun=hook.result.current.request();secondRun=hook.result.current.request().catch(error=>error)});expect((await secondRun).message).toContain('Refresh');expect(state.invoke).toHaveBeenCalledTimes(2);await act(async()=>{task.resolve({data:ack(mutation,{status:'pending_review',revision:first,requestedAt:date,eligibleAfter:due}),error:null});await firstRun});expect(hook.result.current.state?.status).toBe('pending_review');});
  it.each(['account','profile','pause','unmount'])('retires late mutation after %s',async kind=>{const task=pending<any>();let mutation:any;state.invoke.mockImplementation(async(_name,request)=>{if(request.action==='deletion_status')return{data:ack(request),error:null};mutation=request;return task.promise});const hook=renderHook(()=>useAccountDeletion());await waitFor(()=>expect(hook.result.current.ready).toBe(true));let operation!:Promise<any>;await act(async()=>{operation=hook.result.current.request().catch(error=>error)});await act(async()=>{if(kind==='unmount')hook.unmount();else if(kind==='pause')window.dispatchEvent(new Event('app-paused'));else{state.epoch++;if(kind==='account')state.uid='bob';state.profile='different';hook.rerender()}});await act(async()=>{task.resolve({data:ack(mutation,{status:'pending_review',revision:first,requestedAt:date,eligibleAfter:due}),error:null});expect(await operation).toBeInstanceOf(Error)});if(kind!=='unmount')expect(hook.result.current.state?.status).not.toBe('pending_review');});
  it('does not dispatch offline or while native paused',async()=>{Object.defineProperty(navigator,'onLine',{configurable:true,value:false});await expect(checkedDeletionRequest(scope,{action:'deletion_status'})).rejects.toThrow('online');Object.defineProperty(navigator,'onLine',{configurable:true,value:true});window.dispatchEvent(new Event('app-paused'));await expect(checkedDeletionRequest(scope,{action:'deletion_status'})).rejects.toThrow('online');expect(state.invoke).not.toHaveBeenCalled();});
  it('bounds a stalled status read to fifteen seconds',async()=>{vi.useFakeTimers();state.invoke.mockReturnValue(new Promise(()=>{}));const result=checkedDeletionRequest(scope,{action:'deletion_status'}).catch(error=>error);await vi.advanceTimersByTimeAsync(15000);expect((await result).message).toContain('timed out');});
  it('never displays legacy profile purge dates as confirmed deletion state',async()=>{state.invoke.mockImplementation(async(_name,request)=>({data:ack(request,{status:'review_required'}),error:null}));render(<AccountDangerZone/>);await screen.findByText(/Your deletion request needs support review/);expect(screen.queryByText('Deletion request recorded')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Request account deletion with a 30-day grace period'})).not.toBeInTheDocument();});
});
