import {act,cleanup,renderHook,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import type {ReactNode} from 'react';
const state=vi.hoisted(()=>({uid:'alice' as string|undefined,epoch:1,ready:true,authReady:true,read:vi.fn(),docs:vi.fn(),direct:vi.fn(),cache:vi.fn(),disk:vi.fn()}));
const own=()=>state.uid?{id:state.uid+'-profile',user_id:state.uid,username:state.uid,avatar_url:null,bio:'own',created_at:'2026-01-01'}:undefined;
vi.mock('@/lib/auth',()=>({useAuth:()=>({user:state.uid?{id:state.uid}:null,profile:own(),authReady:state.authReady})}));
vi.mock('@/hooks/useProfileAccount',()=>({useProfileAccount:()=>{const uid=state.uid,epoch=state.epoch;return{user:uid?{id:uid}:null,profile:own(),session:{uid,epoch},ready:state.ready&&!!uid,guard:()=>{if(!state.ready||uid!==state.uid||epoch!==state.epoch)throw new Error('Account changed')}}}}));
vi.mock('@/lib/reportModerationService',()=>({reportAccountSnapshot:()=>({uid:state.uid,epoch:state.epoch})}));
vi.mock('@/lib/profileCache',()=>({setCachedProfile:(...args:unknown[])=>state.cache(...args),getCachedCurrentProfile:()=>state.disk()}));
vi.mock('@/hooks/useVisiblePostCount',()=>({useVisiblePostCount:()=>({count:null,label:'—',exact:false})}));
vi.mock('@/lib/firebase/firestoreDb',()=>({where:(field:string,_op:string,value:unknown)=>({field,value}),firestoreLimit:(value:number)=>({limit:value}),getDocumentsFromServer:(...args:unknown[])=>state.docs(...args),getDocumentFromServer:(...args:unknown[])=>state.direct(...args)}));
vi.mock('@/lib/firebase',()=>({db:{from:(table:string)=>{const filters:any[]=[];let count=false;const query:any={select:(_fields:string,options:any)=>{count=!!options?.head;return query},eq:(field:string,value:unknown)=>{filters.push({field,value});return query},limit:()=>query,maybeSingle:()=>state.read({table,filters,count,single:true}),then:(resolve:any,reject:any)=>Promise.resolve(state.read({table,filters,count,single:false})).then(resolve,reject)};return query;},rpc:async()=>({data:null,error:null})}}));
import {useProfileById,useProfileByUsername} from './useProfile';
const bob={id:'bob-profile',user_id:'bob',username:'bob',avatar_url:null,bio:'public fixture',created_at:'2026-01-01'};
function pending<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>resolve=yes);return{promise,resolve}}
const wrapper=(client:QueryClient)=>({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>;
function countReply(request:any){return request.count?{count:3,data:null,error:null}:{data:request.filters.some((filter:any)=>filter.field==='follower_id'&&filter.value==='alice-profile')?{id:'follow'}:null,error:null};}
beforeEach(()=>{vi.clearAllMocks();state.uid='alice';state.epoch++;state.ready=true;state.authReady=true;Object.defineProperty(navigator,'onLine',{configurable:true,value:true});window.dispatchEvent(new Event('app-resumed'));state.docs.mockResolvedValue([bob]);state.direct.mockResolvedValue(bob);state.disk.mockReturnValue(null);state.read.mockImplementation(async request=>request.table==='profiles'?{data:request.single?bob:[bob],error:null}:countReply(request));});
afterEach(()=>{cleanup();vi.useRealTimers();Object.defineProperty(navigator,'onLine',{configurable:true,value:true});window.dispatchEvent(new Event('app-resumed'));});
describe('actual profile read lifetime and auxiliary loading',()=>{
  it('retires a stalled header at the deadline and ignores its reply after a successful explicit retry',async()=>{
    vi.useFakeTimers();const gate=pending<any>();state.docs.mockReturnValueOnce(gate.promise);
    const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});
    await act(async()=>{await vi.advanceTimersByTimeAsync(15001)});
    expect(hook.result.current.isError).toBe(true);expect(hook.result.current.isLoading).toBe(false);
    expect(state.cache).not.toHaveBeenCalled();
    await act(async()=>{await hook.result.current.refetch();await vi.advanceTimersByTimeAsync(1)});
    expect(hook.result.current.data?.id).toBe('bob-profile');const cacheCalls=state.cache.mock.calls.length;
    await act(async()=>{gate.resolve([{...bob,id:'late-profile'}]);await vi.advanceTimersByTimeAsync(1)});
    expect(hook.result.current.data?.id).toBe('bob-profile');expect(state.cache).toHaveBeenCalledTimes(cacheCalls);
  });
  it('bounds the whole username fallback sequence instead of restarting its deadline for each read',async()=>{
    vi.useFakeTimers();const gate=pending<any>();state.docs.mockReturnValueOnce(gate.promise);state.direct.mockReturnValue(new Promise(()=>{}));
    const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});
    await act(async()=>{await vi.advanceTimersByTimeAsync(14000);gate.resolve([]);await vi.advanceTimersByTimeAsync(1)});
    expect(state.direct).toHaveBeenCalledOnce();expect(hook.result.current.isLoading).toBe(true);
    await act(async()=>{await vi.advanceTimersByTimeAsync(1001)});expect(hook.result.current.isError).toBe(true);
  });
  it('settles slow counts without replacing an available header when their deadline expires',async()=>{
    vi.useFakeTimers();const gate=pending<void>();state.read.mockImplementation(request=>gate.promise.then(()=>countReply(request)));
    const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});
    await act(async()=>{await vi.advanceTimersByTimeAsync(5)});expect(hook.result.current.data?.id).toBe('bob-profile');
    await act(async()=>{await vi.advanceTimersByTimeAsync(15001)});expect(hook.result.current.statsError).toBe(true);expect(hook.result.current.statsPending).toBe(false);
    await act(async()=>{gate.resolve();await vi.advanceTimersByTimeAsync(1)});
    expect(hook.result.current.data?.following_count_label).toBe('—');expect(hook.result.current.isError).toBe(false);
  });
  it('paints an ID profile before slow follow counts complete',async()=>{const gate=pending<void>();state.read.mockImplementation(request=>request.table==='profiles'?Promise.resolve({data:bob,error:null}):gate.promise.then(()=>countReply(request)));const hook=renderHook(()=>useProfileById('bob-profile'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.data?.id).toBe('bob-profile'));expect(hook.result.current.isLoading).toBe(false);expect(hook.result.current.data?.following_count_label).toBe('—');await act(async()=>{gate.resolve()});await waitFor(()=>expect(hook.result.current.data?.following_count).toBe(3));});
  it('uses the already checked current owner profile without another profile lookup',async()=>{const hook=renderHook(()=>useProfileByUsername('alice'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.data?.id).toBe('alice-profile'));expect(state.docs).not.toHaveBeenCalled();expect(state.direct).not.toHaveBeenCalled();expect(state.read.mock.calls.some(([request])=>request.table==='profiles')).toBe(false);});
  it('cannot reuse another viewer’s follow status after an account switch',async()=>{const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.data?.is_following).toBe(true));await act(async()=>{state.uid='charlie';state.epoch++;hook.rerender()});expect(hook.result.current.data?.is_following).not.toBe(true);await waitFor(()=>expect(hook.result.current.data?.id).toBe('bob-profile'));await waitFor(()=>expect(hook.result.current.data?.is_following).toBe(false));});
  it('discards delayed identity without warming its cache after native pause, then resumes a fresh read',async()=>{const gate=pending<any>();state.docs.mockReturnValueOnce(gate.promise);const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(state.docs).toHaveBeenCalledOnce());await act(async()=>{window.dispatchEvent(new Event('app-paused'));gate.resolve([bob])});expect(hook.result.current.data).toBeUndefined();expect(state.cache).not.toHaveBeenCalled();expect(state.read).not.toHaveBeenCalled();await act(async()=>{window.dispatchEvent(new Event('app-resumed'))});await waitFor(()=>expect(hook.result.current.data?.id).toBe('bob-profile'));expect(state.docs).toHaveBeenCalledTimes(2);});
  it('cannot apply late counts after A to B to A retirement',async()=>{const gate=pending<void>();state.read.mockImplementation(request=>gate.promise.then(()=>countReply(request)));const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(state.read).toHaveBeenCalledTimes(3));await act(async()=>{state.uid='charlie';state.epoch++;hook.rerender()});await waitFor(()=>expect(state.docs).toHaveBeenCalledTimes(2));await act(async()=>{state.uid='alice';state.epoch++;hook.rerender()});await waitFor(()=>expect(state.docs).toHaveBeenCalledTimes(3));expect(hook.result.current.data?.is_following).not.toBe(true);await act(async()=>{gate.resolve()});await waitFor(()=>expect(hook.result.current.data?.following_count).toBe(3));});
  it('does not dispatch manual refetch during native pause or offline',async()=>{window.dispatchEvent(new Event('app-paused'));const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await act(async()=>{await hook.result.current.refetch()});expect(state.docs).not.toHaveBeenCalled();expect(state.read).not.toHaveBeenCalled();expect(hook.result.current.data).toBeUndefined();});
  it('does not turn a denied profile read into a missing profile or more fallback requests',async()=>{state.docs.mockRejectedValue(new Error('Permission denied'));const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.isError).toBe(true));expect(hook.result.current.data).toBeUndefined();expect(state.direct).not.toHaveBeenCalled();expect(state.docs).toHaveBeenCalledOnce();});
  it('rejects ambiguous usernames instead of selecting the first identity',async()=>{state.docs.mockResolvedValue([bob,{...bob,id:'duplicate'}]);const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.isError).toBe(true));expect(state.cache).not.toHaveBeenCalled();expect(state.direct).not.toHaveBeenCalled();});
  it('deduplicates lowercase lookups and retains checked legacy Auth UID routes',async()=>{state.docs.mockImplementation(async(_table,filters)=>filters[0].field==='user_id'?[bob]:[]);state.direct.mockResolvedValue(null);const hook=renderHook(()=>useProfileByUsername('legacy-uid'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.data?.id).toBe('bob-profile'));expect(state.docs).toHaveBeenCalledTimes(2);expect(state.direct).toHaveBeenCalledOnce();});
  it('keeps a failed statistics read separate from the loaded header',async()=>{state.read.mockResolvedValue({data:null,count:null,error:{message:'No counts'}});const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await waitFor(()=>expect(hook.result.current.statsError).toBe(true));expect(hook.result.current.data?.id).toBe('bob-profile');expect(hook.result.current.data?.following_count_label).toBe('—');expect(hook.result.current.isError).toBe(false);});
  it('never uses a disk profile as a checked placeholder during a pending read',async()=>{state.disk.mockReturnValue({...bob,bio:'stale private'});state.docs.mockReturnValue(new Promise(()=>{}));const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});expect(hook.result.current.data).toBeUndefined();expect(state.disk).not.toHaveBeenCalled();});
  it('waits for current signed-in profile readiness instead of falling back to a guest lookup',async()=>{state.ready=false;const hook=renderHook(()=>useProfileByUsername('bob'),{wrapper:wrapper(new QueryClient())});await act(async()=>{await hook.result.current.refetch()});expect(state.docs).not.toHaveBeenCalled();expect(state.direct).not.toHaveBeenCalled();});
});
