// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Test if localStorage is available (fails in iOS Private Browsing, some in-app browsers)
const isLocalStorageAvailable = (() => {
  try {
    const testKey = '__storage_test__';
    localStorage.setItem(testKey, '1');
    localStorage.removeItem(testKey);
    return true;
  } catch {
    console.warn('[Auth] localStorage unavailable, falling back to sessionStorage');
    return false;
  }
})();

// Export for debugging
export const storageStatus = {
  localStorageAvailable: isLocalStorageAvailable,
  usingFallback: !isLocalStorageAvailable,
};

// Custom storage adapter with fallback to sessionStorage
const customStorage = {
  getItem: (key: string): string | null => {
    try {
      const storage = isLocalStorageAvailable ? localStorage : sessionStorage;
      return storage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      const storage = isLocalStorageAvailable ? localStorage : sessionStorage;
      storage.setItem(key, value);
    } catch {
      console.error('[Auth] Storage blocked - session will NOT persist across tabs/reloads');
    }
  },
  removeItem: (key: string): void => {
    try {
      const storage = isLocalStorageAvailable ? localStorage : sessionStorage;
      storage.removeItem(key);
    } catch {
      // Ignore errors
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: 'vybe-auth-token',
  }
});