import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const state=vi.hoisted(()=>({uid:'alice',profileId:'profile-alice',epoch:1,collect:vi.fn(),success:vi.fn(),error:vi.fn(),download:vi.fn(),createUrl:vi.fn(),revokeUrl:vi.fn()}));
vi.mock('@/lib/auth',()=>({useAuth:()=>({user:{id:state.uid},profile:{id:state.profileId,user_id:state.uid},signOut:vi.fn()})}));
vi.mock('@/lib/firebase',()=>({db:{functions:{invoke:vi.fn()}}}));
vi.mock('@/lib/accountDataExport',()=>({collectAccountDataExport:(...args:any[])=>state.collect(...args)}));
vi.mock('sonner',()=>({toast:{success:state.success,error:state.error}}));
vi.mock('@/hooks/useVerifiedSettingsScope',()=>({useVerifiedSettingsScope:()=>({account:{uid:state.uid,epoch:state.epoch},profileId:state.profileId,creationTime:'2026-01-01',ready:true,capture:()=>{const uid=state.uid,id=state.profileId,epoch=state.epoch;return {fields:{expectedOwnerUid:uid,expectedProfileId:id,expectedAccountCreatedAt:1},guard:()=>{if(uid!==state.uid||id!==state.profileId||epoch!==state.epoch)throw new Error('Retired')}}}})}));
import { AccountDangerZone } from './AccountDangerZone';
function pending<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes});return{promise,resolve}}
beforeEach(()=>{vi.clearAllMocks();state.uid='alice';state.profileId='profile-alice';state.epoch++;state.collect.mockResolvedValue(new Blob(['export']));state.createUrl.mockReturnValue('blob:test');Object.defineProperty(URL,'createObjectURL',{configurable:true,value:state.createUrl});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:state.revokeUrl});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(state.download)});
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks()});
describe('guarded personal export download',()=>{
  it('downloads only the completed checked Blob and retires its object URL',async()=>{vi.useFakeTimers();render(<AccountDangerZone/>);await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Export your account data as JSON'}))});expect(state.collect).toHaveBeenCalledWith('alice','profile-alice',expect.any(Function));expect(state.download).toHaveBeenCalledOnce();expect(state.createUrl).toHaveBeenCalledOnce();expect(state.revokeUrl).not.toHaveBeenCalled();await act(async()=>{await vi.advanceTimersByTimeAsync(1500)});expect(state.revokeUrl).toHaveBeenCalledWith('blob:test');expect(state.success).toHaveBeenCalledWith('Your data export is ready.')});
  it('prevents overlapping export clicks before React rerenders',async()=>{const task=pending<Blob>();state.collect.mockReturnValue(task.promise);render(<AccountDangerZone/>);const button=screen.getByRole('button',{name:'Export your account data as JSON'});await act(async()=>{fireEvent.click(button);fireEvent.click(button)});expect(state.collect).toHaveBeenCalledOnce();await act(async()=>{task.resolve(new Blob(['ready']))});expect(state.download).toHaveBeenCalledOnce()});
  it('creates no partial download after export failure and offers an explicit retry',async()=>{state.collect.mockRejectedValueOnce(new Error('The export was interrupted.'));render(<AccountDangerZone/>);await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Export your account data as JSON'}))});expect(state.createUrl).not.toHaveBeenCalled();expect(state.download).not.toHaveBeenCalled();expect(state.error).toHaveBeenCalledWith('The export was interrupted.');expect(screen.getByRole('button',{name:'Export your account data as JSON'})).toBeEnabled();await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Export your account data as JSON'}))});expect(state.download).toHaveBeenCalledOnce()});
  it.each(['account','profile','unmount'])('cannot download a late export after %s retirement',async kind=>{const task=pending<Blob>();state.collect.mockReturnValue(task.promise);const view=render(<AccountDangerZone/>);await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Export your account data as JSON'}))});if(kind==='unmount')view.unmount();else{state.epoch++;if(kind==='account')state.uid='bob';state.profileId='new-profile';view.rerender(<AccountDangerZone/>)}await act(async()=>{task.resolve(new Blob(['private']))});expect(state.createUrl).not.toHaveBeenCalled();expect(state.download).not.toHaveBeenCalled();expect(state.success).not.toHaveBeenCalled();expect(state.error).not.toHaveBeenCalled()});
});
