# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
