// Shared rotating tips shown in loaders and splash screen.
export const VYBE_TIPS: string[] = [
  'Long-press a message to react with any emoji',
  'Swipe right on a message to quick-reply',
  'Hold the camera button to record a Snap',
  'Your VYBE DNA evolves the more you use the app',
  'Pull down on the feed to refresh',
  'Tap an avatar to peek their Vibe Check',
  'Earn XP every day you log in — streaks count',
  'Star a chat to keep it pinned to the top',
  'Tap the V at any time to jump home',
  'Drag a sticker onto a post to react publicly',
  'Spotlight search finds anything in two taps',
  'Themes you love can be shared with friends',
  'Mute notifications per-chat from the chat menu',
  'Your Daily Brief updates at 6am, noon, and 6pm',
  'Slow connection? VYBE auto-retries in the background',
  'Double-tap a post to drop a quick like',
  'Long-press the V logo for a secret debug menu',
  'Customize your bento grid by dragging blocks',
  'Send a VYBE Snap — it disappears after one view',
  'Friends nearby? Open the Friend Map to see them',
  'Hold to record voice notes in any DM',
  'Pinch to zoom on any photo or clip',
  'Swipe up on a profile to see their posts',
  'Your Aura reflects how you interact with others',
  'Pin up to 3 posts to the top of your profile',
  'Use @mentions to tag friends in group chats',
  'Schedule posts for the perfect time to drop',
  'Vibe Check sets a 4-hour mood ring on your avatar',
  'Earn coins by completing daily quests',
  'Trade themes, stickers, and sounds in the Locker',
  'Tap and hold a notification for quick actions',
  'Shake your phone to send instant feedback',
  'Your weekly recap drops every Sunday',
  'Reply with a GIF — tap the smiley in any chat',
  'Long-press a clip to save it to your Collections',
  'Group calls support up to 8 friends at once',
  'Ghost Mode hides your location from the map',
  'Streaks reset at midnight your local time',
  'Boost a friend\'s post to share it to your feed',
  'Tap the weather icon to swap your background',
  'Your VYBE Pro perks unlock extra customization',
  'Swipe left on the feed for Local-only posts',
  'Reactions, polls and stickers all earn XP',
  'Hold on a friend\'s avatar to send them a nudge',
];
